# Generated by Django 3.2.10 on 2022-03-07 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_choose_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='choose_user',
            field=models.ManyToManyField(related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
