# Generated by Django 3.2.10 on 2022-03-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_choose_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='choose_user',
        ),
        migrations.AddField(
            model_name='customer',
            name='choose_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
